### ISSUE TITLE
Error with installing on RedMine 4.0.6

### ISSUE THREAD

**Issue by Rez1ce** [masamitsu-murase/redmine_add_subversion_links#14]
Redmine version                4.0.6.stable
  Ruby version                   2.7.0-p0 (2019-12-25) [x86_64-linux-gnu]
  Rails version                  5.2.3
  Subversion                     1.13.0

RedMine just won't launch from apache2 and i get error 500 (from log files)

**Comment by masamitsu-murase** [comment]
Unfortunately, version 0.6.0 does not support Redmine 4.0 and later.
I will release version 0.7.0 soon to support Redmine 4.0 and later.

**Comment by masamitsu-murase** [comment]
c1a16552654da088ff1b0870f50683faac93e7bf fixes this issue.

I released version 0.7.0 for Redmine 4.0 and later.
Please download it from [plugin page](https://www.redmine.org/plugins/add_subversion_links#0.7.0).

Regards,
Murase
